"""Load and query the compiled knowledge bundle shipped inside the app.

The bundle (knowledge/rules.json) is generated by `spl-critic compile` at
build time — this module never parses YAML or markdown on the Splunk host.

Runs on Splunk's bundled Python 3.9: annotations stay behind the future
import; no 3.10+ runtime features.
"""

from __future__ import annotations

import json
import os
from typing import Any

_KNOWLEDGE_DIR = os.path.join(os.path.dirname(__file__), "knowledge")


def load_bundle(path: str | None = None) -> dict[str, Any]:
    """Load rules.json (rules + policy modes + limits + command types)."""
    bundle_path = path or os.path.join(_KNOWLEDGE_DIR, "rules.json")
    with open(bundle_path) as f:
        return json.load(f)


def load_fragments(path: str | None = None) -> dict[str, Any]:
    """Load prompt_fragments.json (per-rule prompt text + few-shot pairs)."""
    fragments_path = path or os.path.join(_KNOWLEDGE_DIR, "prompt_fragments.json")
    with open(fragments_path) as f:
        return json.load(f)


def rule_index(bundle: dict[str, Any]) -> dict[str, dict[str, Any]]:
    """Map every code — primary ids and aliases — to its rule record."""
    index: dict[str, dict[str, Any]] = {}
    for rule in bundle["rules"]:
        index[rule["id"]] = rule
        for alias in rule.get("aliases", []):
            index[alias] = rule
    return index


def max_severity(codes: list[str], bundle: dict[str, Any]) -> str | None:
    """Highest severity among the given codes; None when codes is empty."""
    if not codes:
        return None
    order = bundle["verdict_policy"]["severity_order"]
    index = rule_index(bundle)
    return max((index[c]["severity"] for c in codes), key=order.index)


def verdict_for_codes(codes: list[str], bundle: dict[str, Any]) -> dict[str, Any]:
    """The unified Tier 1 scoring contract: one honest verdict from a set of
    finding codes — max severity vs the single policy threshold, scores from
    max rule weights. No per-role modes: critique is not a dial.
    """
    policy = bundle["verdict_policy"]
    order = policy["severity_order"]
    index = rule_index(bundle)

    severity = max_severity(codes, bundle)
    verdict = "approved"
    if severity is not None:
        rank = order.index(severity)
        block_at = policy["block_at"]
        if block_at is not None and rank >= order.index(block_at):
            verdict = "blocked"
        elif rank >= order.index(policy["warn_at"]):
            verdict = "warn"

    return {
        "verdict": verdict,
        "risk_score": max([index[c]["risk_weight"] for c in codes] or [0]),
        "cost_score": max([index[c]["cost_weight"] for c in codes] or [0]),
        "reasons": [
            {"code": index[c]["id"], "message": index[c]["name"], "severity": index[c]["severity"]}
            for c in codes
        ],
    }
